// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "t_user"

// User mapped from table <t_user>
type User struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName        string    `gorm:"column:user_name;not null" json:"user_name"`
	Password        string    `gorm:"column:password;not null" json:"password"`
	Mail            string    `gorm:"column:mail;not null" json:"mail"`
	PhoneRegionNum  int32     `gorm:"column:phone_region_num;not null;default:86" json:"phone_region_num"`
	PhoneNum        string    `gorm:"column:phone_num;not null" json:"phone_num"`
	CreateTime      time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time" json:"update_time"`
	IsBan           bool      `gorm:"column:is_ban;not null" json:"is_ban"`
	IsLogOut        bool      `gorm:"column:is_log_out;not null" json:"is_log_out"`
	CreateTimeStamp int64     `gorm:"column:create_time_stamp" json:"create_time_stamp"`
	UpdateTimeStamp int64     `gorm:"column:update_time_stamp" json:"update_time_stamp"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
